### ISSUE TITLE
Pypager Not Showing UTF-8 characters. 

### ISSUE THREAD

**Issue by Werner1201** [jonathanslenders/pypager#10] opened 2020-04-11 04:24 UTC
I've been working on a little project that I can parse the name, chapter or chapters and verses or no verses of the bible, and I am using clint to color my text, but When I pipe it to pypager the "çèéêôâãõ" characters of my source are not even being shown. 
![image](https://user-images.githubusercontent.com/8631657/79035213-a7454d80-7b92-11ea-81a9-6fecd1f3cab7.png)
On the Image where it shows Gnesis it should be Gênesis. 
If you want to try yourself to see if I'm being just dumb here's the repo where this project is: [https://github.com/Werner1201/PyBible](https://github.com/Werner1201/PyBible)
I think I don't need to say to create a virtual env and download the requirements, since you're much more experienced than me. If you help me with that I'd be grateful.

**Comment by jonathanslenders** [comment] 2020-04-11 20:51
Can you try this:
```
echo  "çèéêôâãõ"  | pypager
```
This should work normally. (It does on my system.) If that doesn't work, we know the issue is not in your code.

Instead of using pypager, can you pipe the output to a file, and then verify the encoding of that file? Or see whether it works with "less" or "more"?

**Comment by Werner1201** [comment] 2020-04-11 20:56
I'll do that test, but the part of working with less isn't possible since I'm on Windows. I will try piping to more but I'd really like to have the functionality of less. When I get home I'll post the results

**Comment by Werner1201** [comment] 2020-04-12 01:54
So when I try to pipe the output of echo to a file like this: 
![image](https://user-images.githubusercontent.com/8631657/79058514-7a05a780-7c45-11ea-8f4c-2c7db95e599c.png)
I get this result: 
![image](https://user-images.githubusercontent.com/8631657/79058521-90abfe80-7c45-11ea-880a-a532ab0e0ebf.png)
When I pipe it to more on vscode terminal: 
![image](https://user-images.githubusercontent.com/8631657/79058685-90acfe00-7c47-11ea-93ed-e95be4d89857.png)
When I pipe it on Cmder:
![image](https://user-images.githubusercontent.com/8631657/79058559-fd26fd80-7c45-11ea-8ff8-3408ae105cf2.png)
When I pipe it on Native Command Prompt:
![image](https://user-images.githubusercontent.com/8631657/79058585-3eb7a880-7c46-11ea-8624-7e5f08972afe.png)
When I use the first test: `echo  "çèéêôâãõ"  | pypager` on a executable file:
![image](https://user-images.githubusercontent.com/8631657/79058619-7d4d6300-7c46-11ea-9c6b-b95fb207e0a0.png)
But... There's a catch when I quit I saw this:
![image](https://user-images.githubusercontent.com/8631657/79058626-9c4bf500-7c46-11ea-92aa-f0456b209baf.png)
When I try the code directly on the terminal: 
![image](https://user-images.githubusercontent.com/8631657/79058639-d5846500-7c46-11ea-97ed-a4649d87f440.png)
When I exit: 
![image](https://user-images.githubusercontent.com/8631657/79058642-e59c4480-7c46-11ea-8e39-0fbd3700d9c5.png)

I have no Idea where the problem might come from. I don't know if it is some weird windows command line bug or my system is not configured correctly and how I should configure it.
I would be very grateful if you help me with this, since I'm a beginner on python coding and the peculiarities of dealing with the command line on python.

**Comment by jonathanslenders** [comment] 2020-04-15 19:30
Can you try pypager from this branch: https://github.com/prompt-toolkit/pypager/pull/11  ?
I noticed that we don't take sys.stdin.encoding into account. On Windows, this is often not utf-8, but we were always reading from stdin using utf-8.

**Comment by Werner1201** [comment] 2020-04-15 19:50
How can I try this ? should I just make pip update this module ?
or should I download the repo and exchange the pypager folder from my venv?

**Comment by jonathanslenders** [comment] 2020-04-15 19:53
I have merged it in the "master" branch.
You can clone the repository:
```
git clone https://github.com/prompt-toolkit/pypager.git
```
Then go into that directory, and run: ``pip install -e .``

**Comment by Werner1201** [comment] 2020-04-15 20:03
Result of running out of the environment the code:
![image](https://user-images.githubusercontent.com/8631657/79383110-057b8300-7f3b-11ea-8690-2670dd289d30.png)
![image](https://user-images.githubusercontent.com/8631657/79383130-10ceae80-7f3b-11ea-8f38-10e8b44cf5ec.png)

**Comment by Werner1201** [comment] 2020-04-15 20:05
When I run it from a .cmd file:
![image](https://user-images.githubusercontent.com/8631657/79383288-54291d00-7f3b-11ea-8661-8437f3f154ba.png)

**Comment by Werner1201** [comment] 2020-04-15 20:06
is this the expected result ?

**Comment by jonathanslenders** [comment] 2020-04-15 20:10
I can reproduce it. It's not expected.

**Comment by Werner1201** [comment] 2020-04-15 20:12
![image](https://user-images.githubusercontent.com/8631657/79383833-3f00be00-7f3c-11ea-84c8-d69b2a2bc91b.png)
Look like it makes my program wok, I ran the script like this: 
![image](https://user-images.githubusercontent.com/8631657/79383885-550e7e80-7f3c-11ea-9da3-2d6efb31ef63.png)

**Comment by jonathanslenders** [comment] 2020-04-15 20:13
I get the same weird characters when running this on Windows:
```
echo "çáóéú" | python -c "import sys;print(sys.stdin.read())"
```
![image](https://user-images.githubusercontent.com/216638/79383863-34f3b500-7f66-11ea-84e3-7cd73b2fca9c.png)

I'm not yet sure what's the precise reason. sys.stdin.encoding is cp1252.

**Comment by Werner1201** [comment] 2020-04-15 20:15
Always encoding, the english speaking people have it so much easier. just kidding, but encoding is always a problem when dealing with reading and piping stuff on cmd, specially if you use this "special characters"

**Comment by Werner1201** [comment] 2020-04-15 20:16
When I was on College, my professors always avoided righting those characters on C.

**Comment by Werner1201** [comment] 2020-04-15 20:19
I could close the issue here, since my program is displaying the characters correcly, but I don't mind helping investigating since I plan to run this program on another computer.

**Comment by Werner1201** [comment] 2020-04-15 20:22
Try changing the language of your system to portuguese Brazil, maybe it changes when changing the language.

**Comment by Werner1201** [comment] 2020-04-15 20:23
althought, it would be too much work to see if this little thing starts to show the same thing.

**Comment by jonathanslenders** [comment] 2020-04-15 21:25
If I get it right, for some reason Python thinks the input encoding is cp1252 when data is piped into stdin, while actually it is cp437. Not utf-8.

![image](https://user-images.githubusercontent.com/216638/79390610-4f329080-7f70-11ea-8149-98fcbf1d66de.png)

This could be a Python bug, but I'm not 100% sure.

**Comment by Werner1201** [comment] 2020-04-15 21:27
If it is, might be cool to report that, since they might fix it on a newer
version.

Em qua, 15 de abr de 2020 18:25, Jonathan Slenders <notifications@github.com>
escreveu:

**Comment by jonathanslenders** [comment] 2020-04-15 21:32
Running this in the console, before doing the pipe or using pypager should fix it:
```
chcp 1252
```

**Comment by Werner1201** [comment] 2020-04-15 21:34
Alright, I think the issue can be closed. If I was on my computer I would
close it.

Em qua, 15 de abr de 2020 18:32, Jonathan Slenders <notifications@github.com>
escreveu:

**Comment by jonathanslenders** [comment] 2020-04-15 21:57
So, I think Python changes the encoding to cp1252 during startup, while the data that's passed over the pipe still uses cp437.
Possibly related: https://www.python.org/dev/peps/pep-0528/

I don't know of syscalls to detect the encoding of a file handle.
I'll close the issue for now, as we have a workaround.

**Closed as completed by jonathanslenders** 2020-04-15 21:57 UTC
